# Global variables
variables:
  project_name: "Documentation - Isogeo To Office"
  project_name_clean: "isogeo2office"
  yarn_cache_folder: $(Pipeline.Workspace)/.yarn/cache

trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - "*"

pr:
- master

jobs:
- job: 'Build'
  pool:
    vmImage: "ubuntu-latest"
  
  steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '10.15.x'
    displayName: 'Install Node.js 10.15.x'
 
  - task: CacheBeta@0
    continueOnError: true
    inputs:
      key: "isogeo-help-yarn-$(Agent.OS)"
      path: $(yarn_cache_folder)
    displayName: 'Cache Yarn packages'

  - script: yarn global add gitbook
    displayName: 'Install Gitbook'

  - script: yarn install --frozen-lockfile --ignore-engines
    displayName: 'Install dependencies'

  - script: yarn gitbook install
    displayName: 'Install Gitbook dependencies'

  - script: yarn gitbook build ./ dist/
    displayName: 'Build Gitbook HTML output'

  - task: DeleteFiles@1
    displayName: 'Remove files to be ignored in publication'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        azure-pipelines.yml
        package.json
        yarn.lock

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: $(project_name)'
    inputs:
      path: $(System.DefaultWorkingDirectory)/dist
      artifact: '$(project_name)_$(Build.SourceBranchName)_$(Build.Id)'

# PUBLISH TO QA
# only with a tagged commit (see: https://github.com/MicrosoftDocs/vsts-docs/issues/3281)
- job: 'PublishQA'
  displayName: "Publish to QA"
  dependsOn: 'Build'
  pool:
    vmImage: "windows-2019"

  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: '$(project_name)_$(Build.SourceBranchName)_$(Build.Id)'
      targetPath: '$(System.DefaultWorkingDirectory)/book_to_upload'

  - task: AzureFileCopy@3
    inputs:
      cleanTargetBeforeCopy: true
      SourcePath: '$(System.DefaultWorkingDirectory)/book_to_upload'
      azureSubscription: 'Isogeo - MPN(82885610-5841-4749-8d71-46f56b643ad2)'
      Destination: 'AzureBlob'
      storage: 'qaisogeohelp'
      ContainerName: '$web'
      BlobPrefix: '$(project_name_clean)'

# PUBLISH
# only with a tagged commit (see: https://github.com/MicrosoftDocs/vsts-docs/issues/3281)
- job: 'PublishPROD'
  displayName: "Publish to PROD"
  dependsOn: 'Build'
  pool:
    vmImage: "windows-2019"
  condition:
    contains(variables['Build.SourceBranch'], 'tags')

  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: '$(project_name)_$(Build.SourceBranchName)_$(Build.Id)'
      targetPath: '$(System.DefaultWorkingDirectory)/book_to_upload'

#  - task: GitHubRelease@1
#    inputs:
#      gitHubConnection: 'github_isogeo'
#      repositoryName: '$(Build.Repository.Name)'
#      action: 'edit'
#      target: '$(Build.Id)'
#      changeLogCompareToRelease: 'lastFullRelease'
#      changeLogType: 'issueBased'

  - task: AzureFileCopy@3
    inputs:
      cleanTargetBeforeCopy: true
      SourcePath: '$(System.DefaultWorkingDirectory)/book_to_upload'
      azureSubscription: 'Isogeo - MPN(82885610-5841-4749-8d71-46f56b643ad2)'
      Destination: 'AzureBlob'
      storage: 'prodisogeohelp'
      ContainerName: '$web'
      BlobPrefix: '$(project_name_clean)'