trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - "*"

pr:
- master

jobs:
- job: 'Build'
  pool:
    vmImage: "windows-2019"
  
  steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '10.15.x'
    displayName: 'Install Node.js 10.15.x'
 
  # - task: CacheBeta@0
  #   inputs:
  #     key: yarn | $(Agent.OS) | $(Build.SourcesDirectory)/yarn.lock
  #     path: $(Pipeline.Workspace)/.cache/yarn
  #   displayName: 'Cache yarn packages'

  - script: yarn global add gitbook
    displayName: 'Install Gitbook'

  - script: yarn
    displayName: 'Install dependencies'

  - script: yarn build ./ dist/
    displayName: 'Build Gitbook HTML output'
